[package]
name = "dead_split_rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
global-hotkey = "0.6.3"
livesplit-core = { git = "https://github.com/LiveSplit/livesplit-core", features = ["auto-splitting"] }
godot = "0.2.3"